### PR TITLE
Upgrade Camel component, connector, and assemblies to Camel 4

### PR DESCRIPTION
**Pull request by fhcarter**
_Note --  this is the merge of the Camel 4 staging branch into master.  All the changes contained herein have been separately reviewed as they moved into the staging branch.  So this should be mostly a formality._

Upgrades the version of Camel used to version 4.4.3;  version 4.4.3 is the current long-term support (LTS) version.  There were some API changes to Camel, but not that many.

The bigger changes, generally, were the upgrade to Java 17, required by Camel v4.  Also, this upgrades the supported test framework to JUnit 5.  Since we use this framework, upgrades were required here as well.

Upgraded our assembly generation code and supporting resources.  Most of this was innocuous: places where the kamelets (from which our assemblies are generated) changed names of parameters, added new things, changed route definitions, etc. 

Note that the set of assemblies has changed.  Camel 3 had around 160 assemblies; Camel 4 has around 180 (_sinks_ and _sources_ -- we don't build assemblies out of _actions_).  Some have gone away, other added.  This isn't something we decided for any reason, just what's available in camel-land.

Once this is approved & merged, I'll publish the connector docker image for this version to quay.io and update our staging & dev catalogs with the updated assemblies.

### CODE REVIEW

**Comment by fhcarter** [comment]
[Jenkins run](https://jenkins.vantiq.com/jenkins/job/vantiq-extension-sources-branch/262/)

**Comment by fhcarter** [comment]
If anyone has the bandwidth to take a look at this, I'd appreciate it.  This is a roll-up PR of the staging branch, where the commits (via PR) the staging branch have been reviewed separately.

Thanks

**Review by sfitts — APPROVED** [review]
LGTM

**Comment by sfitts** [comment]
Since the individual changes have been reviewed, I see no need to rereview them here.  Approved to make the process gods happy.  If there is something you'd like someone to look at, we can do that too.

**Comment by fhcarter** [comment]
Fair enough -- wasn't sure what the process was in this case.  In the future, I'll treat reviewed staging-branch type things similar to ports of changes.  Thx

**Comment by sfitts** [comment]
> Fair enough -- wasn't sure what the process was in this case. In the future, I'll treat reviewed staging-branch type things similar to ports of changes. Thx

That's my usual approach -- unless I see something in the combined merge that looks off/tricky (for example, if I had to resolve some major conflicts or something).

**Pull request merged**
