### PR TITLE
Select different IP camera for tests

### LINKED ISSUE #471: ObjRec: testIpCamera tests hanging sporadically
Issue appears to be with CalTrans/WC camera.  Sometimes it's fine, sometimes it just hangs on open.

Finding simpler camera.

(Note: _WC_ camera == _Walnut Creek_ camera, for those of you who may attempt to misinterpret!)

### PR DESCRIPTION
**Pull request by fhcarter**
Fix #471

Select different camera -- CalTrans/WC @ Main camera/software sometimes hangs on open.  Select different, simpler camera.

### CODE REVIEW

**Comment by fhcarter** [comment]
[Jenkins run](https://jenkins.vantiq.com/jenkins/job/vantiq-extension-sources-branch/226/)

**Comment by fhcarter** [comment]
@rblumer4 & @AlexBlumer : This should fix the hang.  We'll know in an hour or so...

Running that test locally, it was sporadic -- ran about half the time, hung the other half.  Don't know if they have some issue with routing or updated the software on the CalTrans camera @ 680 & Main (which was the hanging camera).  Found a simpler camera on insecam.org, so we'll see if that holds up for a while.

**Review by AlexBlumer — APPROVED** [review]
LGTM, assuming tests pass

**Comment by fhcarter** [comment]
Test run complete & clean.  Hopefully, this'll fix things....

**Pull request merged**
