### PR TITLE
PythonExecSource: Bump aiohttp to 3.9.5, and catch up to vantiq sdk's

### LINKED ISSUE #479: pythonExecSource: Bump version of aiohttp & vantiqsdk
CVE and vantiqconnectorsdk & vantiqsdk upgrade due to their bumps of aiohttp.

### PR DESCRIPTION
**Pull request by fhcarter**
Fixes #479

AioHttp is dependabot warning.

Vantiq SDK's upgraded for analogous Dependabot warning (or our application thereof)

### CODE REVIEW

**Comment by fhcarter** [comment]
[Jenkins run](https://jenkins.vantiq.com/jenkins/job/vantiq-extension-sources-branch/229/) -- clean

**Comment by fhcarter** [comment]
bump

**Review by sfitts — APPROVED** [review]
LGTM

**Comment by fhcarter** [comment]
Updated pypi repo.

**Pull request merged**
